### ISSUE TITLE
Cannot Acknowledge Problems

### ISSUE THREAD

**Issue by gregkeys** [bodsch/docker-icingaweb2#20]
icinga web 2.4.2 using this docker image

getting the following error when trying to acknowledge a problem
```shell
icinga: Empty reply from server.

#0 /usr/share/webapps/icingaweb2-2.4.2/modules/monitoring/application/forms/Command/Object/AcknowledgeProblemCommandForm.php(162): Icinga\Module\Monitoring\Command\Transport\CommandTransport->send(Object(Icinga\Module\Monitoring\Command\Object\AcknowledgeProblemCommand))
#1 /usr/share/webapps/icingaweb2-2.4.2/library/Icinga/Web/Form.php(1158): Icinga\Module\Monitoring\Forms\Command\Object\AcknowledgeProblemCommandForm->onSuccess()
#2 /usr/share/webapps/icingaweb2-2.4.2/modules/monitoring/library/Monitoring/Web/Controller/MonitoredObjectController.php(129): Icinga\Web\Form->handleRequest()
#3 /usr/share/webapps/icingaweb2-2.4.2/modules/monitoring/application/controllers/HostController.php(119): Icinga\Module\Monitoring\Web\Controller\MonitoredObjectController->handleCommandForm(Object(Icinga\Module\Monitoring\Forms\Command\Object\AcknowledgeProblemCommandForm))
#4 /usr/share/webapps/icingaweb2-2.4.2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Monitoring\Controllers\HostController->acknowledgeProblemAction()
#5 /usr/share/webapps/icingaweb2-2.4.2/library/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('acknowledgeProb...')
#6 /usr/share/webapps/icingaweb2-2.4.2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#7 /usr/share/webapps/icingaweb2-2.4.2/library/Icinga/Application/Web.php(389): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#8 /usr/share/webapps/icingaweb2-2.4.2/library/Icinga/Application/webrouter.php(109): Icinga\Application\Web->dispatch()
#9 /usr/share/webapps/icingaweb2-2.4.2/public/index.php(4): require_once('/usr/share/weba...')
#10 {main}
```

the console error is as follows:
```
VM40:1 POST https://example.com/icinga/monitoring/host/acknowledge-problem?host=%5BUser%20Acceptance%20Testing%5D%20example-uat 500 (Internal Server Error)
(anonymous) @ VM40:1
send @ icinga.min.js:4
ajax @ icinga.min.js:4
loadUrl @ icinga.min.js:105
submitForm @ icinga.min.js:199
dispatch @ icinga.min.js:3
r.handle @ icinga.min.js:3
icinga.min.js:30 4:14:59 PM.200 500 Internal Server Error:  Error icinga: Empty reply from server. #0 /usr/share/webapps/icingaweb2-2.4.2/modules/monitoring/ap
```

**Comment by gregkeys** [comment]
fixed by adding container hostnames and container_names that more closely matched the docker-compose example
