### ISSUE TITLE
better support for icingaweb2-module-vspheredb

### ISSUE THREAD

**Issue by bodsch** [bodsch/docker-icingaweb2#29]
We need an better support or integration of `icingaweb2-module-vspheredb`

With the previous integration we run into the error that added vcenters are not initialized automatically.
So I built a workaround that periodically queries the database.
For entries whose `vcenter_id == NULL`, an `icingacli vspheredb task initialize --serverId $id` is explicitly called.
For this a bugfix at Icinga should be opened if necessary (?)

**Comment by bodsch** [comment]
i integrate an watch job as workaround for a daemon problem.
this job works (for me and my maschine), but has an strange side-effect.
After delet an vcenter instance over the UI, it comes to PHP stacktraces like this:
```
icingaweb2        | [2019-02-05 15:28:13] DEBUG remove sync task for vcenter.coremedia.com (pid: 1591)
icingaweb2        | /init/runtime/watch_vspheredb.sh: line 104:  1591 Terminated              /usr/bin/icingacli vspheredb task sync --vCenterId ${vcenter_id}
icingaweb2        | [2019-02-05 15:28:13] DEBUG           - remove lockfile /tmp/vspheredb_vcenter.coremedia.com_sync.lock
icingaweb2        | 2019/02/05 15:29:10 [error] 615#615: *12 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught ErrorException: Creating default object from empty value in /usr/share/webapps/icingaweb2-2.6.2/library/Icinga/Web/Controller/ActionController.php:127
icingaweb2        | Stack trace:
icingaweb2        | #0 /usr/share/webapps/icingaweb2-2.6.2/library/Icinga/Web/Controller/ActionController.php(127): Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(2, 'Creating defaul...', '/usr/share/weba...', 127, Array)
icingaweb2        | #1 /usr/share/webapps/icingaweb2-2.6.2/library/Icinga/Web/Controller/Dispatcher.php(59): Icinga\Web\Controller\ActionController->__construct(Object(Icinga\Web\Request), Object(Icinga\Web\Response), Array)
icingaweb2        | #2 /usr/share/webapps/icingaweb2-2.6.2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
icingaweb2        | #3 /usr/share/webapps/icingaweb2-2.6.2/library/Icinga/Application/Web.php(300): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
icingaweb2        | #4 /usr/share/webapps/icingaweb...
icingaweb2        | PHP message: PHP Fatal error:  Uncaught ErrorException: Uncaught ErrorException: Creating default object from empty value in /usr/share/webapps/icingaweb2-2.6.2/library/Icinga/Web/Controller/ActionController.php:127
icingaweb2        | Stack trace:
icingaweb2        | #0 /usr/share/webapps/icingaweb2-2.6.2/library/Icinga/Web/Controller/ActionController.php(127): Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(2, 'Creating defaul...', '/usr/share/weba...', 127, Array)
icingaweb2        | #1 /usr/share/webapps/icingaweb2-2.6.2/library/Icinga/Web/Controller/Dispatcher.php(59): Icinga\Web\Controller\ActionController->__construct(Object(Icinga\Web\Request), Object(Icinga\Web\Response), Array)
icingaweb2        | #2 /usr/share/webapps/icingaweb2-2.6.2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
icingaweb2        | #3 /usr/share/webapps/icingaweb2-2.6.2/library/Icinga/Application/Web.php(300): Zend_Controller_Front->dispatch(
```

And fragments from the (deleted) vcenter (VMs, Datacenters, ...) are still present in the database
